---

foreman_provisioning_password: changeme
foreman_admin_password: changeme
foreman_hostname: foreman
foreman_subdomain: example.org
foreman_fqdn: '{{ foreman_hostname }}.{{ foreman_subdomain }}'
fedora_content_mirror: "dl.fedoraproject.org/fedora-alt"
foreman_cert_dest: /tmp/foreman_ca_crt.pem

authorized_keys: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

foreman_dns_interface: "{{ ansible_default_ipv4.interface }}"
foreman_network_facts: "{{ vars['ansible_' + foreman_dns_interface] }}"
foreman_ip: "{{ foreman_network_facts.ipv4.address }}"
foreman_subnet: "{{ foreman_network_facts.ipv4.network }}"
foreman_proxy_dns_reverse: "{{ (foreman_subnet | ipaddr('revdns'))[2:-1] }}"
foreman_dns_forwarders: '{{ ansible_dns.nameservers }}'

fedora_boot_content_url: "http://"

fedora_rsync_boot_files: no
fedora_boot_file_url_base: "dl.fedoraproject.org/pub/alt"
fedora_content_host: '{{ foreman_fqdn + "/fedora_atomic" if fedora_rsync_boot_files else fedora_boot_file_url_base }}'
