---
cluster_subdomain: example.org

storage_metadata_replicas: 3
storage_data_replicas: 3
storage_block_create: false
storage_block_default: false
storage_cephfs_create: true
storage_cephfs_default: true
