---
- name: Install epel-release
  yum:
    name: epel-release
    state: present

- name: Disable swap
  command: swapoff -a
  tags: ['skip_ansible_lint']

- name: Disable swap on reboot
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Disable selinux
  command: setenforce 0
  tags: ['skip_ansible_lint']

- name: Disable selinux on reboot
  selinux:
    state: permissive
    policy: targeted

- import_tasks: networking.yml

- import_tasks: docker_centos.yml

- import_tasks: kubernetes_centos.yml
