ansible_become: true
ansible_ssh_user: root

os_update: true

openshift_master_default_subdomain: "apps.{{ foreman_subdomain }}"
# etcd_image: quay.io/coreos/etcd:latest
openshift_deployment_type: origin
containerized: true
openshift_use_system_containers: true
openshift_disable_check: memory_availability
openshift_image_tag: v3.9.0
openshift_master_identity_providers: [{'name': 'htpasswd_auth','login': 'true', 'challenge': 'true','kind': 'AllowAllPasswordIdentityProvider'}]
openshift_schedulable: true
openshift_set_hostname: true
ansible_python_interpreter: /usr/bin/python3

openshift_master_node_labels:
  node-role.kubernetes.io/master: 'true'
  node-role.kubernetes.io/compute: 'true'

openshift_master_open_ports:
- service: dns tcp
  port: 53/tcp
- service: dns udp
  port: 53/udp

openshift_node_open_ports:
- service: dns tcp
  port: 53/tcp
- service: dns udp
  port: 53/udp

ansible_service_broker_registry_whitelist:
  - '.*'
