---
###########################################################################
# User variables                                                          #
###########################################################################

# Change this to an IP range reserved on your network
metallb_ip_range: '192.168.17.100-192.168.17.200'

# Make sure these numbers are <= the number of disks available in your cluster
storage_data_replicas: 3
storage_metadata_replicas: 3

# Change this to the subdomain you're using for your cluster services
cluster_subdomain: example.org

helm_version: v3.2.1

deploy_murmur: true

###########################################################################
# Project variables                                                       #
# -----------------                                                       #
# These should work as-is, modification is still possible but it will be  #
# very easy to break things                                               #
###########################################################################
master_node_schedulable: false

# Set to true to create CephBlockStorage
storage_block_create: false
# Set to true to make block storage the default storageclass
storage_block_default: false
# Set to true to make a CephFilesystem
storage_cephfs_create: true
# Set to true to make cephfs the default storageclass
storage_cephfs_default: true

artifacts_dir: "{{ (playbook_dir + '/../artifacts') | realpath }}"
