---
###########################################################################
# User variables                                                          #
###########################################################################

openshift_installer_image_org: homecluster
openshift_installer_image_tag: latest
pull_policy: Always
ansible_ssh_extra_args : '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'

###########################################################################
# Project variables                                                       #
# -----------------                                                       #
# These should work as-is, modification is still possible but it will be  #
# very easy to break things                                               #
###########################################################################
openshift_host: 'https://{{ groups.first_master.0 }}:8443'
master_subdomain: '{{ groups.first_master.0.split(".")[1:] | join(".") }}'
