---
###########################################################################
# User variables                                                          #
###########################################################################

openshift_installer_image_org: openshift
openshift_installer_image_tag: v3.10
pull_policy: Always

###########################################################################
# Project variables                                                       #
# -----------------                                                       #
# These should work as-is, modification is still possible but it will be  #
# very easy to break things                                               #
###########################################################################
openshift_host: 'https://{{ groups.first_master.0 }}:8443'
master_subdomain: '{{ groups.first_master.0.split(".")[1:] | join(".") }}'

awx_credential_file: /tmp/awx_credentials

tower_resources:
  - resource: organization
    content:
      '-n': home-cluster
  - resource: project
    content:
      '-n': openshift-ansible
      '--organization': home-cluster
      '--scm-type': git
      '--scm-url': https://github.com/openshift/openshift-ansible.git
      '--wait': ""
  - resource: inventory
    content:
      '-n': home-cluster
      '--organization': home-cluster
  - resource: credential
    content:
      '-n': home-cluster
      '--organization': home-cluster
      '--credential-type': Machine
      '--inputs': '@{{ awx_credential_file }}'
  - resource: job_template
    content:
      '-n': scaleup
      '-i': home-cluster
      '--job-type': run
      '--project': openshift-ansible
      '--playbook': playbooks/openshift-node/scaleup.yml
      '--credential': home-cluster
      '--verbosity': verbose
      '--become-enabled': true
      '--allow-simultaneous': false
