---

- name: clone projects
  hosts: foreman
  tasks:
  - name: clone projects
    git:
      repo: https://github.com/theforeman/forklift.git
      dest: '{{ playbook_dir + "/" + 'forklift' }}'

- include: forklift/playbooks/katello.yml

- name: post-config
  hosts: foreman
  tasks:
    - name: open ports
      firewalld:
        port: '{{ item }}'
        state: enabled
        permanent: true
        immediate: true
      with_items:
        - 53/tcp
        - 67-69/udp
        - 80/tcp
        - 443/tcp
        - 3000/tcp
        - 3306/tcp
        - 5910-5930/tcp
        - 5432/tcp
        - 8140/tcp
        - 8443/tcp

    - name: pull down foreman discovery images
      command: foreman-installer --foreman-plugin-discovery-install-images=true

    - name: Reboot
      shell: shutdown -r +1
      async: 0
      poll: 0

    - name: "Wait for reboot"
      local_action: wait_for
      args:
        host: "{{ inventory_hostname }}"
        port: 22
        state: started
        delay: 60
        timeout: 3600
