---

- name: Wait for discovered hosts
  block:
  - include_tasks: hosts.yml
    with_sequence: count=100
    loop_control:
      loop_var: num_iterations
  rescue:
  - fail: msg="Discovery failed..."
    when: not discovery_success
