- name: Create {{ name|default('') }} {{ resource }}
  command: hammer {{ resource }} create {{ options }}
  register: result
  failed_when: result.rc |int > 0 and 'already been taken' not in result.stderr
  changed_when: "'already been taken' not in result.stderr"

- name: "{{ name|default('') }} {{ resource }} was already present, update instead"
  command: hammer {{ resource }} update {{ options }}
  when: "'already been taken' in result.stderr"
  ignore_errors: true
