---

- name: rsync Fedora Atomic 26 content for pxe boot
  command: |
    /usr/bin/rsync
      --delay-updates -F
      --compress
      --archive
      --include '/atomic'
      --include '/atomic/stable'
      --include '/atomic/stable/Fedora-Atomic-26-20170723.0'
      --include '/atomic/stable/Fedora-Atomic-26-20170723.0/Atomic'
      --include '/atomic/stable/Fedora-Atomic-26-20170723.0/Atomic/x86_64'
      --include '/atomic/stable/Fedora-Atomic-26-20170723.0/Atomic/x86_64/os'
      --include '/atomic/stable/Fedora-Atomic-26-20170723.0/Atomic/x86_64/os/**'
      --exclude '*'
      --out-format='<<CHANGED>>%i %n%L'
      rsync://dl.fedoraproject.org/fedora-alt /var/lib/foreman/public/fedora-atomic-26


- name: make template dir
  file:
    path: /tmp/templates/
    state: directory
    mode: 0777

- name: Copy templates
  copy:
    src: "{{ item }}"
    dest: "/tmp/templates/{{ item.split('/')[-1] }}"
  with_fileglob:
    - '*'

- include: create_or_update.yml
  vars:
    name: Fedora Atomic 26 Mirror
    resource: medium
    options: |
      --name "Fedora Atomic 26 Mirror"
      --os-family "Redhat"
      --path "http://{{ inventory_hostname }}/fedora-atomic-26/atomic/stable/Fedora-Atomic-26-20170723.0/Atomic/x86_64/os/"


- include: create_or_update.yml
  vars:
    name: Discovery PXELinux Template
    resource: template
    options: |
      --name "Discovery PXELinux Template"
      --type "PXELinux"
      --locked "no"
      --file /tmp/templates/template_DiscoveryPXEBoot

- include: create_or_update.yml
  vars:
    name: Fedora Atomic 26 Kickstart
    resource: template
    options: |
      --name "Fedora Atomic 26 Kickstart"
      --type "provision"
      --locked "no"
      --file /tmp/templates/template_FedoraAtomicKickstart


- include: create_or_update.yml
  vars:
    name: Fedora-Atomic
    resource: os
    options: |
      --family "Redhat"
      --name "Fedora-Atomic"
      --major "26"
      --partition-tables 'Kickstart default'
      --architectures x86_64
      --media "Fedora Atomic 26 Mirror"
      --provisioning-templates 'Kickstart default PXELinux,Fedora Atomic 26 Kickstart'
      --config-templates 'Kickstart default PXELinux,Fedora Atomic 26 Kickstart'

- name: Associate templates with OS
  command: |
    hammer template add-operatingsystem
      --name "{{ item }}"
      --operatingsystem 'Fedora-Atomic 26'
  with_items:
    - 'Fedora Atomic 26 Kickstart'
    - 'Kickstart default PXELinux'
  register: result
  failed_when: result.rc |int > 0 and 'already been taken' not in result.stderr
  changed_when: "'already been taken' not in result.stderr"

- include: create_or_update.yml
  vars:
    name: home.fabianism.us
    resource: domain
    options: |
      --dns-id 1
      --name home.fabianism.us

- include: create_or_update.yml
  name: production
  vars:
    resource: environment
    options: "--name production"

- include: create_or_update.yml
  vars:
    name: default
    resource: subnet
    options: |
      --name default
      --network 192.168.1.0
      --mask 255.255.255.0
      --dns-id 1
      --dns-primary 192.168.1.45
      --domain-ids 1
      --tftp-id 1

- include: create_or_update.yml
  vars:
    name: openshift-nodes
    resource: hostgroup
    options: |
        --architecture "x86_64"
        --name "openshift-nodes"
        --operatingsystem "Fedora-Atomic 26"
        --environment "production"
        --partition-table "Kickstart default"
        --root-pass '{{ foreman_provisioning_password }}'
        --domain-id 1
        --subnet "default"
        --puppet-ca-proxy-id 1
        --puppet-proxy-id 1
        --medium "Fedora Atomic 26 Mirror"
        --pxe-loader '{{ pxe_loader | default("PXELinux BIOS")}}'

- include: create_or_update.yml
  vars:
    name: default
    resource: discovery-rule
    options: |
      --enabled yes
      --hostgroup "openshift-nodes"
      --hostname "node<%=@host.facts['ipaddress'].split('.')[-1] %>"
      --name "default"
      --search "*"

- name: Update settings
  command: |
    hammer settings set
      --name "{{ item.key }}"
      --value "{{ item.value }}"
  with_items:
    - key: 'global_PXELinux'
      value: 'Discovery PXELinux Template'
    - key: 'ansible_ssh_pass'
      value: '{{ foreman_provisioning_password }}'
    - key: 'discovery_auto'
      value: 'true'
    - key: 'safemode_render'
      value: 'false'

# TODO need to get OS to associate properly
- name: Rebuild pxe default
  command: hammer template build-pxe-default
