---

- name: make template dir
  file:
    path: /tmp/templates/
    state: directory
    mode: 0777

- name: Copy templates
  copy:
    src: "{{ item }}"
    dest: "/tmp/templates/{{ item.split('/')[-1] }}"
  with_fileglob:
    - '*'

- name: Create Fedora Atomic 26 installation medium
  command: |
    hammer medium create
      --name "Fedora Atomic 26 Mirror"
      --os-family "Redhat"
      --path "https://dl.fedoraproject.org/pub/alt/atomic/stable/Fedora-Atomic-26-20170723.0/Atomic/x86_64/os/"
  register: result
  failed_when: result.rc |int > 0 and 'already been taken' not in result.stderr
  changed_when: "'already been taken' not in result.stderr"

- name: Create discovery PXELinux template
  command: |
    hammer template create
      --name "Discovery PXELinux Template"
      --type "PXELinux"
      --locked "no"
      --file /tmp/templates/template_DiscoveryPXEBoot
  register: result
  failed_when: result.rc |int > 0 and 'already been taken' not in result.stderr
  changed_when: "'already been taken' not in result.stderr"

- name: Create Fedora Atomic 26 Kickstart template
  command: |
    hammer template create
      --name "Fedora Atomic 26 Kickstart"
      --type "provision"
      --locked "no"
      --file /tmp/templates/template_FedoraAtomicKickstart
  register: result
  failed_when: result.rc |int > 0 and 'already been taken' not in result.stderr
  changed_when: "'already been taken' not in result.stderr"

- name: Create Fedora Atomic 26 Operating System
  command: |
    hammer os create
      --family "Redhat"
      --name "Fedora-Atomic"
      --major "26"
      --partition-tables 'Kickstart default'
      --architectures x86_64
      --media "Fedora Atomic 26 Mirror"
      --provisioning-templates 'Kickstart default PXELinux,Fedora Atomic 26 Kickstart'
  register: result
  failed_when: result.rc |int > 0 and 'already exists' not in result.stderr
  changed_when: "'already exists' not in result.stderr"

- name: Associate templates with OS
  command: |
    hammer template add-operatingsystem
      --name "{{ item }}"
      --operatingsystem 'Fedora-Atomic 26'
  with_items:
    - 'Fedora Atomic 26 Kickstart'
    - 'Kickstart default PXELinux'
  register: result
  failed_when: result.rc |int > 0 and 'already been taken' not in result.stderr
  changed_when: "'already been taken' not in result.stderr"

- name: Create the openshift-nodes hostgroup
  command: |
    hammer hostgroup create
      --architecture "x86_64"
      --name "openshift-nodes"
      --operatingsystem "Fedora-Atomic 26"
      --environment "production"
      --architecture "x86_64"
      --partition-table "Kickstart default"
      --root-pass '{{ foreman_provisioning_password }}'
  register: result
  failed_when: result.rc |int > 0 and 'already been taken' not in result.stderr
  changed_when: "'already been taken' not in result.stderr"

- name: Create default discovery provision rules
  command: |
    hammer discovery-rule create
      --enabled yes
      --hostgroup "openshift-nodes"
      --hostname "node<%=@host.facts['ipaddress'].split('.')[-1] %>"
      --name "default"
      --search "*"
  register: result
  failed_when: result.rc |int > 0 and 'already been taken' not in result.stderr
  changed_when: "'already been taken' not in result.stderr"

- name: Update settings
  command: |
    hammer settings set
      --name "{{ item.key }}"
      --value "{{ item.value }}"
  with_items:
    - key: 'global_PXELinux'
      value: 'Discovery PXELinux Template'
    - key: 'ansible_ssh_pass'
      value: '{{ foreman_provisioning_password }}'
    - key: 'discovery_auto'
      value: 'true'
