---

- block:
  - set_fact:
      fedora_atomic_version_suffix: '{{ "-" + fedora_version|string if fedora_version is defined else ""}}'

  - shell: >
      curl https://download.fedoraproject.org/pub/alt/atomic/stable -L
      | grep "Fedora-Atomic{{ fedora_atomic_version_suffix }}"
      | tail -n1
      |  sed -rn 's|.*<a href="(.*)/">.*|\1|p'
    register: latest_fedora_response

  - shell: echo {{ latest_fedora_response.stdout }} | awk -F "-" '{print $3}'
    register: fedora_number_raw

  - set_fact:
      fedora_version: '{{ fedora_number_raw.stdout }}'
      fedora_full_version_string: '{{ latest_fedora_response.stdout }}'

  - set_fact:
      fedora_boot_content_url: "http://{{ fedora_content_host }}/atomic/stable/{{ fedora_full_version_string }}/Atomic/x86_64/os/"
  run_once: yes
