---

- name: Disable selinux
  selinux:
    state: disabled

- name: install packages
  package:
    name: '{{ item }}'
  with_items:
    - centos-release-scl
    - epel-release
    - "https://yum.theforeman.org/releases/1.15/el7/x86_64/foreman-release.rpm"
    - foreman-installer
    - tfm-rubygem-hammer_cli_foreman_discovery

- name: print foreman command
  debug:
    msg: |
      foreman-installer
        --foreman-admin-password={{ foreman_admin_password }}
        --enable-foreman-plugin-ansible
        --enable-foreman-plugin-discovery
        --enable-foreman-proxy
        --foreman-proxy-tftp=true
        --foreman-proxy-tftp-servername={{ ansible_default_ipv4['address'] }}
        --foreman-proxy-dns=true
        --foreman-proxy-dns-interface={{ ansible_default_ipv4['interface'] }}
        --foreman-proxy-dns-zone={{ foreman_subdomain }}
        --foreman-proxy-dns-reverse=1.168.192.in-addr.arpa
        --foreman-proxy-dns-forwarders={{ ansible_dns['nameservers'][0] }}
        --foreman-proxy-foreman-base-url=https://foreman.{{ foreman_subdomain }}
        --foreman-proxy-oauth-consumer-key N5h7s5WidswbqEVDwNfxaqh55owfcE62
        --foreman-proxy-oauth-consumer-secret btCrdngjsfeA3VGpXTEFGT6pr5yXeYq9

- name: Run foreman installer
  command: |
    foreman-installer
      --foreman-admin-password={{ foreman_admin_password }}
      --enable-foreman-plugin-ansible
      --enable-foreman-plugin-discovery
      --enable-foreman-proxy
      --foreman-proxy-tftp=true
      --foreman-proxy-tftp-servername={{ ansible_default_ipv4['address'] }}
      --foreman-proxy-dns=true
      --foreman-proxy-dns-interface={{ ansible_default_ipv4['interface'] }}
      --foreman-proxy-dns-zone={{ foreman_subdomain }}
      --foreman-proxy-dns-reverse=1.168.192.in-addr.arpa
      --foreman-proxy-dns-forwarders={{ ansible_dns['nameservers'][0] }}
      --foreman-proxy-foreman-base-url=https://foreman.{{ foreman_subdomain }}
      --foreman-proxy-oauth-consumer-key N5h7s5WidswbqEVDwNfxaqh55owfcE62
      --foreman-proxy-oauth-consumer-secret btCrdngjsfeA3VGpXTEFGT6pr5yXeYq9

- name: Download foreman discovery images
  command: foreman-installer --foreman-plugin-discovery-install-images=true

- name: open ports
  firewalld:
    port: '{{ item }}'
    state: enabled
    permanent: true
    immediate: true
  with_items:
    - 53/tcp
    - 53/udp
    - 67-69/udp
    - 80/tcp
    - 443/tcp
    - 3000/tcp
    - 3306/tcp
    - 5910-5930/tcp
    - 5432/tcp
    - 8140/tcp
    - 8443/tcp

- name: Enable foreman service
  service:
    name: foreman
    enabled: yes
    state: started

- include: fedora-atomic-26.yml
