---

- import_tasks: fedora_version_facts.yml

- name: Enable centos 7 atomic repo
  yum_repository:
    name: centos-atomic-host
    description: Centos Atomic Packages
    baseurl: "https://buildlogs.centos.org/centos/7/atomic/x86_64/Packages/"
    gpgcheck: no
    state: present

- set_fact:
    gpg_key_url: "https://getfedora.org/static/{{ fedora_gpg_keyfile[fedora_version] }}"
    gpg_key_file: /etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-{{ fedora_version }}-x86_64

- name: Download the fedora {{ fedora_version }} GPG key
  uri:
    url: '{{ gpg_key_url }}'
    dest: '{{ gpg_key_file }}'
    creates: '{{ gpg_key_file }}'

- name: Install the fedora {{ fedora_version }} GPG key
  rpm_key:
    key: '{{ gpg_key_file }}'
    state: present

- name: Install required packages for composing an ostree
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - git
    - ostree
    - rpm-ostree

- name: Clone the fedora ostree project
  git:
    repo: 'https://pagure.io/fedora-atomic.git'
    dest: /tmp/fedora-atomic
    version: f{{ fedora_version }}

- name: Init ostree repo
  command: ostree --repo=/var/lib/foreman/public/atomic init --mode=archive-z2

- name: Compose ostree
  command: rpm-ostree compose tree --repo=/var/lib/foreman/public/atomic /tmp/fedora-atomic/fedora-atomic-host.json
  args:
    creates: '/var/lib/foreman/public/atomic/refs/heads/fedora/{{ fedora_version }}/x86_64/atomic-host'

- name: rsync Fedora Atomic {{ fedora_version }} content for pxe boot
  when: fedora_rsync_boot_files
  command: |
    /usr/bin/rsync
      --delay-updates -F
      --compress
      --archive
      --include '/atomic'
      --include '/atomic/stable'
      --include '/atomic/stable/{{ fedora_full_version_string }}'
      --include '/atomic/stable/{{ fedora_full_version_string }}/Atomic'
      --include '/atomic/stable/{{ fedora_full_version_string }}/Atomic/x86_64'
      --include '/atomic/stable/{{ fedora_full_version_string }}/Atomic/x86_64/os'
      --include '/atomic/stable/{{ fedora_full_version_string }}/Atomic/x86_64/os/**'
      --exclude '*'
      --out-format='<<CHANGED>>%i %n%L'
      rsync://{{ fedora_content_mirror }} /var/lib/foreman/public/fedora-atomic
