---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: murmur-db
  labels:
    app: murmur
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: murmur-config
  labels:
    app: murmur
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
