---
apiVersion: v1
kind: Service
metadata:
  name: murmur
  labels:
    app: murmur
spec:
  ports:
    - name: murmur-udp
      port: 64738
      protocol: UDP
    - name: murmur-tcp
      port: 64738
      protocol: TCP
  selector:
    app: murmur
---
apiVersion: v1
kind: Service
metadata:
  name: murmur-port
  labels:
    app: murmur
spec:
  type: NodePort
  ports:
    - name: murmur-udp
      port: 64738
      protocol: UDP
    - name: murmur-tcp
      port: 64738
      protocol: TCP
  selector:
    app: murmur
