---
apiVersion: v1
kind: Namespace
metadata:
  name: mediacenter
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: series
spec:
  accessModes:
  - ReadWriteMany
  - ReadOnlyMany
  capacity:
    storage: 50Ti
  nfs:
    path: /export/series
    server: omv.home.fabianism.us
  storageClassName: nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: movies
spec:
  accessModes:
  - ReadWriteMany
  - ReadOnlyMany
  capacity:
    storage: 50Ti
  nfs:
    path: /export/movies
    server: omv.home.fabianism.us
  storageClassName: nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads
spec:
  accessModes:
  - ReadWriteMany
  - ReadOnlyMany
  capacity:
    storage: 50Ti
  nfs:
    path: /export/downloads
    server: omv.home.fabianism.us
  storageClassName: nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: series
  namespace: mediacenter
  labels:
    app: mediacenter
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  storageClassName: nfs
  volumeName: series
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movies
  namespace: mediacenter
  labels:
    app: mediacenter
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  storageClassName: nfs
  volumeName: movies
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
  namespace: mediacenter
  labels:
    app: mediacenter
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  storageClassName: nfs
  volumeName: downloads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: incomplete-downloads
  namespace: mediacenter
  labels:
    app: mediacenter
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  storageClassName: nfs
  volumeName: downloads
