---
- name: Deploy applications to cluster
  hosts: first_node

  vars:
    deploy_murmur: true
    artifacts_dir: "{{ (playbook_dir + '/../artifacts') | realpath }}"

  tasks:
    - import_tasks: tasks/apps/murmur.yml
      when: deploy_murmur
