---
- hosts: first_node
  become: yes

  tasks:
    - name: Install epel-release
      yum:
        name: epel-release
        state: latest

    - name: Install python dependencies for modules
      yum:
        name:
          - libselinux-python
          - python-openshift
        state: latest

    - name: Install Helm
      unarchive:
        src: https://get.helm.sh/helm-v3.2.1-linux-amd64.tar.gz
        dest: /usr/bin
        remote_src: yes
        extra_opts:
          - "--strip-components=1"
          - "linux-amd64/helm"
