---

- import_playbook: prep_inventory.yml

- hosts: first_master
  tasks:
    - name: disable selinux
      command: setenforce 0

    - name: Create foreman dnsmasq entry
      copy:
        content: server=/{{ master_subdomain }}/{{ master_ip }}
        dest: /etc/dnsmasq.d/homecluster-dns.conf

- hosts: localhost
  vars:
    openshift_installer_image_org: openshift
    openshift_installer_image_tag: v3.9
  tasks:
    - name: Get ID of current user
      command: id -u
      register: user_id
      changed_when: false

    - name: restart docker
      service:
        name: docker
        state: restarted

    - name: Install single node openshift
      docker_container:
        name: openshift-ansible
        image: '{{ openshift_installer_image_org }}/origin-ansible:{{ openshift_installer_image_tag }}'
        cleanup: yes
        detach: no
        user: '{{ user_id.stdout }}'
        env:
          INVENTORY_DIR: /tmp/inventory
          OPTS: '--private-key=/opt/app-root/src/.ssh/id_rsa -e @/tmp/config.yml'
          PLAYBOOK_FILE: playbooks/{{ item }}.yml
        volumes:
          - /home/fabian/.ssh/id_rsa:/opt/app-root/src/.ssh/id_rsa:Z,ro
          - '{{ playbook_dir }}/../awx_inventory:/tmp/inventory:Z,ro'
          - /etc/hosts:/etc/hosts:Z,ro
          - /etc/resolv.conf:/etc/resolv.conf:Z,ro
          - '{{ playbook_dir }}/../config.yml:/tmp/config.yml:Z,ro'
      with_items:
        - prerequisites
        - deploy_cluster

    - name: create admin user account
      command: oc adm policy add-cluster-role-to-user cluster-admin admin
      delegate_to: '{{ groups.first_master.0 }}'

    - name: login as admin
      command: oc login -u admin -p admin https://{{ groups.first_master.0 }}:8443 --insecure-skip-tls-verify=true
      ignore_errors: true
