---
- name: Configure Additional Cluster Infrastructure
  hosts: first_node

  vars:
    artifacts_dir: "{{ (playbook_dir + '/../artifacts') | realpath }}"

    cluster_subdomain: example.org
    storage_metadata_replicas: 3
    storage_data_replicas: 3
    storage_block_create: false
    storage_block_default: false
    storage_cephfs_create: true
    storage_cephfs_default: true
  tasks:
    - name: deploy ingress-nginx
      import_role:
        name: k8s-nginx-ingress

    - name: verify ingress is working
      import_role:
        name: k8s-nginx-ingress
        tasks_from: verify.yml

    - name: Store results
      copy:
        content: |
          status: ingress has been successfully configured.
          address: {{ ip }}
          metallb_ip_range: {{ metallb_ip_range }}
        dest: '{{ artifacts_dir }}/results/01-ingress.yml'
      vars:
        ip: '{{ ingress_nginx_svc.resources.0.status.loadBalancer.ingress.0.ip }}'
      delegate_to: localhost

    - import_tasks: tasks/infra/rook.yml
    # TODO: Configure velero backup onto minio NFS gateway
    # - import_tasks: tasks/infra/velero.yml
