---
- name: Configure Additional Cluster Infrastructure
  hosts: first_node

  vars:
    artifacts_dir: "{{ (playbook_dir + '/../artifacts') | realpath }}"

    cluster_subdomain: example.org
    storage_metadata_replicas: 3
    storage_data_replicas: 3
    storage_block_create: false
    storage_block_default: false
    storage_cephfs_create: true
    storage_cephfs_default: true
  tasks:
    - import_tasks: tasks/infra/ingress.yml
    - import_tasks: tasks/infra/rook.yml
    # TODO: Configure velero backup onto minio NFS gateway
    # - import_tasks: tasks/infra/velero.yml
