---
- name: Configure Additional Cluster Infrastructure
  hosts: first_node

  vars:
    artifacts_dir: "{{ (playbook_dir + '/../artifacts') | realpath }}"

  tasks:
    - name: deploy ingress-nginx
      import_role:
        name: k8s_nginx_ingress

    - name: verify ingress is working
      import_role:
        name: k8s_nginx_ingress
        tasks_from: verify.yml

    - name: Store results
      copy:
        content: |
          status: ingress has been successfully configured.
          address: {{ ip }}
          metallb_ip_range: {{ metallb_ip_range }}
        dest: '{{ artifacts_dir }}/results/01-ingress.yml'
      vars:
        ip: '{{ ingress_nginx_svc.resources.0.status.loadBalancer.ingress.0.ip }}'
      delegate_to: localhost

    - name: deploy rook-ceph
      import_role:
        name: k8s_rook_ceph

    - name: verify volume provisioning is working
      import_role:
        name: k8s_rook_ceph
        tasks_from: verify.yml

    - name: Get rook-ceph dashboard password secret
      k8s_info:
        api_version: v1
        kind: Secret
        name: rook-ceph-dashboard-password
        namespace: rook-ceph
      register: k8s_dashboard_password
      no_log: True

    - name: Write dashboard secret to artifacts
      copy:
        content: '{{ k8s_dashboard_password.resources.0.data.password | b64decode }}'
        dest: '{{ artifacts_dir }}/rook_ceph_dashboard_password.txt'
      no_log: True
      delegate_to: localhost

    - name: Store results
      copy:
        content: |
          status: rook-ceph has been successfully configured.
          manager_dashboard_url: rook-ceph.{{ cluster_subdomain }}
          username: admin
          password_file: {{ artifacts_dir }}/rook_ceph_dashboard_password.txt
        dest: '{{ artifacts_dir }}/results/01-storage.yml'
      delegate_to: localhost

    - import_role:
        name: k8s_velero
