---
- hosts: first_node
  become: true

  vars:
    branch: v1.7.0
    nginx_url: "https://raw.githubusercontent.com/nginxinc/kubernetes-ingress/{{ branch }}/deployments/{{ path }}"

  tasks:
    - name: Create namespace and service account
      community.kubernetes.k8s:
        definition: "{{ item }}"
      loop: '{{ lookup("url", nginx_url, split_lines=False) | from_yaml_all | list }}'
      vars:
        path: common/ns-and-sa.yaml

    - name: Create RBAC resources
      community.kubernetes.k8s:
        definition: "{{ item }}"
      loop: '{{ lookup("url", nginx_url, split_lines=False) | from_yaml_all | list }}'
      vars:
        path: rbac/rbac.yaml

    - name: Create default TLS secret
      community.kubernetes.k8s:
        definition: "{{ item }}"
      loop: '{{ lookup("url", nginx_url, split_lines=False) | from_yaml_all | list }}'
      vars:
        path: common/default-server-secret.yaml

    - name: Create NGINX configmap
      community.kubernetes.k8s:
        definition: "{{ item }}"
      loop: '{{ lookup("url", nginx_url, split_lines=False) | from_yaml_all | list }}'
      vars:
        path: common/nginx-config.yaml

    - name: Create VirtualServer CRD
      community.kubernetes.k8s:
        definition: "{{ item }}"
      loop: '{{ lookup("url", nginx_url, split_lines=False) | from_yaml_all | list }}'
      vars:
        path: common/vs-definition.yaml

    - name: Create VirtualServerRoute CRD
      community.kubernetes.k8s:
        definition: "{{ item }}"
      loop: '{{ lookup("url", nginx_url, split_lines=False) | from_yaml_all | list }}'
      vars:
        path: common/vsr-definition.yaml

    - name: Create TransportServer CRD
      community.kubernetes.k8s:
        definition: "{{ item }}"
      loop: '{{ lookup("url", nginx_url, split_lines=False) | from_yaml_all | list }}'
      vars:
        path: common/ts-definition.yaml

    - name: Create GlobalConfiguration CRD
      community.kubernetes.k8s:
        definition: "{{ item }}"
      loop: '{{ lookup("url", nginx_url, split_lines=False) | from_yaml_all | list }}'
      vars:
        path: common/gc-definition.yaml

    - name: Create a GlobalConfiguration object
      community.kubernetes.k8s:
        definition: "{{ item }}"
      loop: '{{ lookup("url", nginx_url, split_lines=False) | from_yaml_all | list }}'
      vars:
        path: common/global-configuration.yaml

    - name: Create the nginx-ingress DaemonSet
      community.kubernetes.k8s:
        definition: "{{ item }}"
      loop: '{{ lookup("url", nginx_url, split_lines=False) | from_yaml_all | list }}'
      vars:
        path: daemon-set/nginx-ingress.yaml
