---

- import_playbook: prep_inventory.yml

- name: If no masters exist, fail out
  hosts: localhost
  connection: local
  tasks:
    - fail: msg="No master registered to foreman"
      when: groups['masters'] | length == 0

- name: Set devices to be configured for gluster on each node
  hosts: nodes
  vars:
    __glusterfs_devices: []
  tasks:
    - name: Generate list of devices if it does not already exist
      when: glusterfs_devices is not defined
      block:
      - set_fact:
          __glusterfs_devices: '{{ __glusterfs_devices + ["/dev/" + item.key] }}'
        with_dict: '{{ ansible_devices }}'
        when:
          - item.key.startswith('sd') or item.key.startswith('vd')
          - not item.key.endswith('a')
      - set_fact:
          glusterfs_devices: '{{ glusterfs_devices | default(__glusterfs_devices) }}'

    - command: wipefs {{ item }} --all --force
      with_items: '{{ glusterfs_devices }}'
      when: glusterfs_wipe is defined and glusterfs_wipe

    - debug:
        msg: "openshift-ansible will attempt to configure the following devices for gluster: {{ glusterfs_devices }}"

- import_playbook: '{{ openshift_ansible_dir|default("/usr/share/ansible/openshift-ansible") }}/playbooks/prerequisites.yml'
- import_playbook: '{{ openshift_ansible_dir|default("/usr/share/ansible/openshift-ansible") }}/playbooks/deploy_cluster.yml'

- hosts: oo_first_master
  gather_facts: false
  tasks:
    - name: Grant cluster-admin permissions to admin user
      command: oc adm policy add-cluster-role-to-user cluster-admin admin

- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: oc login
      command: oc login -u admin -p admin --insecure-skip-tls-verify=true https://{{ groups['oo_first_master'][0] }}:8443
