---

- import_playbook: prep_inventory.yml

- name: If no masters exist, fail out
  hosts: localhost
  connection: local
  tasks:
    - fail: msg="No master registered to foreman"
      when: groups['masters'] | length == 0

- name: fix limits
  hosts: nodes
  tasks:
    - name: Increase allowed number of open files
      pam_limits:
        domain: '*'
        limit_item: nofile
        limit_type: '-'
        value: 64000

- import_playbook: prep_devices.yml
- import_playbook: '{{ openshift_ansible_dir|default("/usr/share/ansible/openshift-ansible") }}/playbooks/prerequisites.yml'
- import_playbook: '{{ openshift_ansible_dir|default("/usr/share/ansible/openshift-ansible") }}/playbooks/deploy_cluster.yml'

- hosts: oo_first_master
  gather_facts: false
  tasks:
    - name: Grant cluster-admin permissions to admin user
      command: oc adm policy add-cluster-role-to-user cluster-admin admin

- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: oc login
      command: oc login -u admin -p admin --insecure-skip-tls-verify=true https://{{ groups['oo_first_master'][0] }}:8443

- hosts: nodes
  gather_facts: false
  roles:
    - reboot
