- name: Prepare inventory
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Template hosts
    copy:
      content: |
          [masters]
          {{ groups.first_master.0 }} 

          [masters:vars]
          ansible_host={{ hostvars[groups.first_master.0].ansible_host }}
          master_subdomain={{ groups.first_master.0.split('.')[1:]|join('.')}}


          [etcd:children]
          masters

          [new_nodes]

          [nodes:children]
          masters
          new_nodes

          [OSEv3:children]
          masters
          nodes
      dest: '{{ playbook_dir }}/../awx_inventory/hosts'
    run_once: yes
