- name: Prepare inventory
  hosts: ansible_runner
  gather_facts: no
  tasks:
  - name: Template foreman.ini
    copy:
      content: |
          [foreman]
          url = https://{{ foreman_hostname }}.{{ foreman_subdomain }}
          user = admin
          password = {{ foreman_admin_password }}
          ssl_verify = False

          [ansible]
          group_patterns = ["{app}-{tier}-{color}",
                      "{app}-{color}",
                      "{app}",
                      "{tier}"]
          group_prefix = foreman_
          # Whether to fetch facts from Foreman and store them on the host
          want_facts = True

          [cache]
          path = .
          max_age = 60
      dest: '{{ inventory_dir}}/foreman.ini'
    run_once: yes
  - name: Template hosts
    copy:
      content: |
          [foreman]
          https://{{ foreman_hostname }}.{{ foreman_subdomain }}

          [masters]

          [masters:children]
          foreman_hostgroup_openshift_nodes_openshift_master

          [etcd:children]
          masters

          [foreman_hostgroup_openshift_nodes_openshift_master]

          [nodes]

          [nodes:children]
          foreman_hostgroup_openshift_nodes
          masters

          [foreman_hostgroup_openshift_nodes]

          [OSEv3:children]
          masters
          nodes
      dest: '{{ inventory_dir}}/home_cluster_hosts'
    run_once: yes

  - meta: refresh_inventory
