- name: Prepare inventory
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Template hosts
    copy:
      content: |
          [masters]
          {{ groups.first_master.0 }} ansible_host={{ hostvars[groups.first_master.0].ansible_host }}

          [etcd:children]
          masters

          [nodes:children]
          masters

          [OSEv3:children]
          masters
          nodes
      dest: '{{ inventory_dir | default(ansible_inventory_sources[0] | dirname) }}/awx_inventory/hosts'
    run_once: yes
