---

- import_playbook: cluster_auth.yml

- hosts: localhost
  connection: local
  vars:
    tower_apb_image: docker.io/homecluster/tower-apb:latest
  vars_files:
    - '{{ playbook_dir }}/../config.yml'
  tasks:
    - name: Install Ansible Tower
      import_role:
        name: run_apb
      vars:
        permissions: cluster
        api_key: '{{ admin_api_token }}'
        host: '{{ openshift_host }}'
        verify_ssl: no
        action: provision
        name: tower-apb
        namespace: home-cluster
        image: '{{ tower_apb_image }}'
        parameters:
          skip_tls_verify: true
          awx_postgresql_emptydir: true
          _apb_plan_id: all-in-one
          namespace: home-cluster
          enable_dangerous_logs: true
          recommended_resources: false

    - name: get awx-compatible inventory
      command: ansible-inventory -i {{ playbook_dir }}/../awx_inventory --list --export -y
      register: awx_inventory

    - name: write inventory to file
      copy:
        content: '{{ awx_inventory.stdout }}'
        dest: /tmp/awx_inventory

- hosts: first_master
  gather_facts: no
  vars_files:
    - '{{ playbook_dir }}/../config.yml'
  tasks:
    - name: Create tower directory
      file:
        path: /tmp/awx
        state: directory

    - name: write tower credential information
      vars:
        sep: "\n  "
      copy:
        content: |
          username: root
          become_method: sudo
          ssh_key_data: |
            {{ lookup("file", "/home/fabian/.ssh/id_rsa").splitlines() | join(sep) }}
        dest: /tmp/awx/credentials

    - name: wait for tower to come up
      debug:
        msg: '{{ ready|length }}/4 report ready: {{ ready|map(attribute="name")|join(",")  }}'
      until: (ready|length) == 4
      retries: 60
      vars:
        ready: '{{ lookup(
          "k8s",
          kind="Pod",
          namespace="home-cluster",
          label_selector="deploymentconfig=awx"
        ).status.containerStatuses|default([]) | selectattr("ready", "eq", true) | list}}'

    - name: Create resources
      command: docker run -v /tmp/awx:/tmp/awx:Z homecluster/tower-cli {{ item.resource }} create {{ params }} --insecure -p password -u admin -h {{ tower_host }}
      retries: 10
      vars:
        tower_host: https://awx-web-svc-home-cluster.apps.{{ master_subdomain }}
        params: '{{ item.content.items() | map("join", " ") | join(" ") }}'
      loop: '{{ tower_resources }}'

    - name: add awx pod to inventory
      add_host:
        name: '{{ lookup("k8s", kind="Pod", namespace="home-cluster", label_selector="name=awx-web-deploy", host=openshift_host, api_key=admin_api_token, verify_ssl=False).metadata.name }}'
        groups: awx
        ansible_user: awx
        oc_container: awx_web
        oc_host: '{{ openshift_host }}'
        oc_namespace: home-cluster
        oc_token: '{{ admin_api_token }}'
        oc_verify_ssl: false

- hosts: awx
  connection: oc
  tasks:
    - name: copy inventory file
      copy:
        src: /tmp/awx_inventory
        dest: /tmp/inventory

    - name: sync inventory
      command: awx-manage inventory_import --inventory-name=home-cluster --source /tmp/inventory
