ansible_ssh_user: root
ansible_ssh_pass: changeme

foreman_installer_additional_options: ""
fedora_content_mirror: "dl.fedoraproject.org/fedora-alt"

authorized_keys: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

foreman_dns_interface: "{{ ansible_default_ipv4.interface}}"
foreman_network_facts: "{{ vars['ansible_' + foreman_dns_interface] }}"
foreman_ip: "{{ foreman_network_facts.ipv4.address }}"
foreman_subnet: "{{ foreman_network_facts.ipv4.network }}"
foreman_proxy_dns_reverse: "{{ (foreman_subnet | ipaddr('revdns'))[2:-1] }}"
